---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  "/v1/users/match-request/{matchId}":
    post:
      tags:
      - group-controller
      operationId: requestMatching
      parameters:
      - name: matchId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/match-condition":
    post:
      tags:
      - match-requirement-controller
      summary: 매칭 조건 설정 api
      operationId: updateMatchRequirement
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/MatchRequirementReq"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/info/nickname":
    post:
      tags:
      - user-controller
      summary: 닉네임 설정 api
      operationId: updateNickname
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/NicknameReq"
        required: true
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/num-count/{matchId}":
    get:
      tags:
      - group-member-controller
      operationId: countGroupMember
      parameters:
      - name: matchId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/match-stage/group":
    get:
      tags:
      - group-member-controller
      operationId: getGroupStatus
      parameters:
      - name: status
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/match-stage/direct":
    get:
      tags:
      - group-member-controller
      operationId: getDirectStatus
      parameters:
      - name: status
        in: query
        required: false
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/match-detail/{matchId}":
    get:
      tags:
      - group-member-controller
      operationId: getDetailMatching
      parameters:
      - name: matchId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/kakao/info":
    get:
      tags:
      - user-controller
      summary: 카카오에서 받아온 사용자 정보 api
      operationId: getKaKaoInformation
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/info":
    get:
      tags:
      - user-controller
      summary: 내 정보 조회 api
      operationId: getUserInformation
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/group":
    get:
      tags:
      - group-controller
      operationId: getGroups
      parameters:
      - name: date
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/group/{matchId}":
    get:
      tags:
      - group-controller
      summary: 그룹 매칭 생성 결과 화면입니다.
      operationId: getGroupMatching
      parameters:
      - name: matchId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/game/schedule":
    get:
      tags:
      - game-information-controller
      summary: 경기 정보 조회 api
      operationId: getUserInformation_1
      parameters:
      - name: date
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/direct":
    get:
      tags:
      - group-controller
      summary: 일대일 매칭 리스트 반환
      operationId: getDirects
      parameters:
      - name: date
        in: query
        required: true
        schema:
          type: string
          format: date
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/v1/users/direct/{matchId}":
    get:
      tags:
      - group-controller
      summary: 일대일 매칭 생성 결과 조회
      operationId: getDirectMatching
      parameters:
      - name: matchId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
  "/auth/login":
    get:
      tags:
      - o-auth-controller
      operationId: login
      parameters:
      - name: code
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/MateballResponseObject"
components:
  schemas:
    MateballResponseObject:
      type: object
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
        data:
          type: object
    MatchRequirementReq:
      type: object
      properties:
        team:
          type: string
          description: 응원하는 팀 이름
        teamAllowed:
          type: string
          description: 응원 팀 허용 여부
          nullable: true
        style:
          type: string
          description: 관람스타일
        genderPreference:
          type: string
          description: 선호 성별
    NicknameReq:
      required:
      - nickname
      type: object
      properties:
        nickname:
          type: string
          description: 설정할 닉네임
