name: Deploy Swagger Docs

on:
  push:
    branches:
      - dev

jobs:
  deploy-swagger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MATEBALL-SWAGGER repository
        uses: actions/checkout@v4
        with:
          repository: MATEBALL/MATEBALL-SWAGGER
          token: ${{ secrets.GITHUB_TOKEN }}
          path: swagger-docs

      - name: Checkout MATEBALL-SERVER repository
        uses: actions/checkout@v4
        with:
          repository: MATEBALL/MATEBALL-SERVER
          token: ${{ secrets.GITHUB_TOKEN }}
          path: server

      - name: Extract Swagger JSON
        run: |
          mkdir -p tmp
          cp server/src/main/resources/static/swagger-ui/swagger.json tmp/swagger.json

      - name: Convert swagger.json to swagger.yaml
        uses: mikefarah/yq@v4
        with:
          cmd: yq eval -P tmp/swagger.json > swagger-docs/swagger.yaml

      - name: Modify title, version, and description
        run: |
          yq eval '(.info.title = "MATEBALL") | 
                   (.info.version = "v1") |
                   (.info.description = "어서오세요 클라선생님들, MATEBALL 스웨거에 오신 것을 환영합니다")' \
          swagger-docs/swagger.yaml -i

      - name: Commit and push updated swagger.yaml
        run: |
          cd swagger-docs
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add swagger.yaml
          git commit -m "[docs] swagger 문서 자동 배포" || echo "No changes to commit"
          git push
